English/urls.py
from django.urls import path
from .views import *


app_name = "English"
urlpatterns = [
    path("", home, name="home"),
    path("vocabulary/", VocabularyView.as_view(), name="vocabulary"),
    path("vocabulary/create", VocabularyCreateView.as_view(), name="create_vocabulary"),
    path("basic_english/", basic_english, name="basic_english"),
    path("basic_english/exercise/<int:unit>", exercise, name="exercise"),
    path("basic_english/content/<int:unit>", content, name="content"),
]

Tables/urls.py
from django.urls import path
from . import views


app_name = "Tables"
urlpatterns = [
    path("", views.home, name="home"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.lobby, name="lobby"),
    path("admin/", admin.site.urls),
    path("Tables/", include("Tables.urls"), name="Tables"),
    path("English/", include("English.urls"), name="English"),
]

English/models.py
from django.db import models

# Create your models here.
class Vocabulary(models.Model):
    word = models.CharField(max_length=50)
    word_class = models.CharField(max_length=50)

English/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse
from .models import *
# Create your views here.


def home(request):
    return render(request, "English/home.html")


def basic_english(request):
    return render(request, "English/basic_english/home.html")


class VocabularyView(ListView):
    model = Vocabulary
    template_name = "English/vocabulary/home.html"
    context_object_name = "vocabularies"


class VocabularyCreateView(CreateView):
    model = Vocabulary
    template_name = "English/vocabulary/create.html"
    fields = ["word", "word_class"]

    def get_success_url(self) -> str:
        return reverse("English:vocabulary")


def exercise(request, unit):
    return render(request, f"English/basic_english/exercises/exercise{unit}.html")


def content(request, unit):
    return render(request, f"English/basic_english/contents/content{unit}.html")

Tables/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'Tables/index.html')

mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def lobby(request):
    return render(request, "mysite/lobby.html")

English/templates/English/basic_english/contents/content10.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 10 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content11.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 11 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content12.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 12 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content13.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 13 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content15.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 15 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content18.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 18 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content19.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 19 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content2.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div class="container">
        <section>
            <div class="inline-block">
                <div class="main-number">
                    2
                </div>
            </div>
            <div class="inline-block">
                <div class="head">
                    NOUN
                    <br>
                    (คำนาม)
                </div>
            </div>
        </section>

        <section>
            <div class="sub-head">
                ความหมาย
            </div>
            <p>
                <b>Noun</b> หมายถึง คำที่ใช้เรียกคน สัตว์ สิ่งของ สถานที่ และคุณสมบัติ รวมถึงชื่อของสิ่งต่างๆ เหล่านี้
                หากพิจารณาตามการนับ คำนามแบ่งออกได้เป็น 2 ประเภทหลัก คือ นามนับได้ (countable noun) และนาม
                นับไม่ได้ (uncountable noun) ทั้งนี้คำนามสามารถแบ่งออกได้เป็นประเภทย่อยอื่นๆ ได้อีกดังตาราง
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black" style="width: 25%;">ประเภท</th>
                    <th class="text-background-white-black" style="width: 49%;">ประเภทย่อย</th>
                    <th class="text-background-white-black" style="width: 26%;">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td rowspan="3" class="text-background-black-white">
                        <b>
                            นามนับได้
                            <br>
                            (Countable Noun)
                        </b>
                        <br>
                        คือ คำนามที่นับจำนวนได้เป็นได้ทั้งเอกพจน์และพหูพจน์
                        อาจนำหน้าด้วย indefinite article (a / an) 
                        หรือจำนวน (two / five) ได้
                    </td>
                    <td class="list">
                            <b>1) Common Noun (นามทั่วไป)</b>
                            <br>
                            ใช้เรียกสิ่งต่างๆ ทั่วไป โดยไม่ชี้เฉพาะเจาะจงว่าเป็นคนไหนหรือสิ่งไหน
                    </td>
                    <td>man, wonman, city, day, month, car, movie, book, university, restaurant</td>
                </tr>
                <tr>
                    <td class="list">
                        <b>2) Proper Noun (นามเฉพาะ)</b>
                        <br>
                        ใช้เรียกสิ่งต่างๆ อย่างเจาะจง และเป็นชื่อเฉพาะที่ขึ้นต้นด้วยตัวใหญ่เสมอ
                    </td>
                    <td>John, Susan, Bangkok, Monday, April, Honda, Harry Potter, Thammasat</td>
                </tr>
                <tr>
                    <td class="list">
                        <b>3) Collective Noun (นามหมวดหมู่)</b>
                        <br>
                        ใช้แสดงหมวดหมู่ มักใช้กับ of + common noun ที่เป็นนามนับได้
                    </td>
                    <td>
                        an <u>army</u> of soldiers
                        <br>
                        two <u>pairs</u> of shoes
                        <br>
                        five <u>groups</u> of people
                    </td>
                </tr>
                <tr>
                    <td rowspan="4" class="text-background-black-white">
                        <b>
                            นามนับไม่ได้
                            <br>
                            (Uncountable Noun)
                        </b>
                        <br>
                        คือ คำนามที่นับจำนวนไม่ได้ใช้เป็นรูปเอกพจน์ และไม่มี article นำหน้า
                    </td>
                    <td class="list">
                        <b>1) Mass Noun(วัตถุนาม)</b>
                        <br>
                        ใช้เรียกสิ่งต่างๆ ที่เป็นกลุ่มก้อนและนับไม่ได้
                    </td>
                    <td>rice, sugar, bread, water, milk, tea, coffee, gold, air</td>
                </tr>
                <tr>
                    <td class="list">
                        <b>2) Abstract Noun (นามธรรม)</b>
                        <br>
                        ใช้เรียกสิ่งต่างๆ ที่ไม่มีตัวตน จับต้องไม่ได้
                    </td>
                    <td>love, happiness, sadness, friendship, sincerity, peace</td>
                </tr>
                <tr>
                    <td><b>3) ชื่อวิชา</b></td>
                    <td>history, biology, economics, English, French, Spanish, golf, tennis, basketball</td>
                </tr>
                <tr>
                    <td><b>4) นามอื่นๆ</b></td>
                    <td>advice, experience, furniture, homework, information, knowledge, luggage, news, traffic, trouble, weather, work</td>
                </tr>
            </table>
        </section>

        <section>
            <div class="sub-head">
                การเปลี่ยนพจน์ของคำนาม
            </div>
            <p>
                เมื่อเราต้องการสื่อความหมายของคำนามที่มีตั้งแต่สองขึ้นไป เราสามารถเปลี่ยนรูปคำนามนับได้ที่เป็นรูปเอกพจน์ให้เป็นรูปพหูพจน์ด้วยวิธีต่างๆ ดังนี้
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black" style="width: 18%;">วิธีการ</th>
                    <th class="text-background-white-black" style="width: 50%">หลักเกณฑ์</th>
                    <th class="text-background-white-black" style="width: 32%;">ตัวอย่าง</th>
                </tr>
                <tr>
                    <th rowspan="3" class="text-background-black-white">เติม -s</th>
                    <td class="list">1) นามทั่วไป</td>
                    <td>car<b>s</b>, pen<b>s</b>, book<b>s</b>, hand<b>s</b>, bag<b>s</b></td>
                </tr>
                <tr>
                    <td class="list">2) นามที่ลงท้ายด้วย o บางคำหรือเมื่อหน้า o เป็นสระ</td>
                    <td>zoo<b>s</b>, radio<b>s</b>, piano<b>s</b>, photo<b>s</b></td>
                </tr>
                <tr>
                    <td class="list">3) นามที่ลงท้ายด้วย y และหน้า y เป็นสระ</td>
                    <td>way<b>s</b>, boy<b>s</b>, day<b>s</b>, key<b>s</b>, toy<b>s</b></td>
                </tr>
                <tr>
                    <th rowspan="4" class="text-background-black-white">เติม -es</th>
                    <td class="list">1) นามที่ลงท้ายด้วย s, ss, sh, ch, x, z</td>
                    <td>bus<b>es</b>, boss<b>es</b>, class<b>es</b>, glass<b>es</b></td>
                </tr>
                <tr>
                    <td class="list">2) นามที่ลงท้ายด้วย o และหน้า o เป็นพยันชนะ</td>
                    <td>tomato<b>es</b>, potato<b>es</b>, buffalo<b>es</b></td>
                </tr>
                <tr>
                    <td class="list">3) นามที่ลงท้ายด้วย y และหน้า y เป็นพยันชนะ เปลี่ยน y เป็น i และเติม es</td>
                    <td>bab<b>ies</b>, stor<b>ies</b>, universit<b>ies</b>, lad<b>ies</b>, countr<b>ies</b>, compan<b>ies</b></td>
                </tr>
                <tr>
                    <td class="list">4) นามที่ลงท้ายด้วย f, fe เปลี่ยนเป็น v แล้วเติม es</td>
                    <td>li<b>ves</b>, lea<b>ves</b>, wi<b>ves</b>, thie<b>ves</b></td>
                </tr>
                <tr>
                    <th class="text-background-black-white">เปลี่ยนสระ หรือเปลี่ยนรูป</th>
                    <td>นามเหล่านี้ไม่มีหลัก ต้องอาศัยการท่องจำ</td>
                    <td>men, women, feet, teeth, geese, policemen, mice, children, oxen</td>
                </tr>
                <tr>
                    <th class="text-background-black-white">ไม่เปลี่ยนรูป</th>
                    <td>นามเหล่านี้ไม่มีหลัก ต้องอาศัยการท่องจำ</td>
                    <td>fish, deef, sheep, series, species</td>
                </tr>
            </table>
        </section>

        <section>
            <div class="sub-head">
                หน้าที่ของคำนาม
            </div>
            <p>
                คำนามสามารถทำหน้าที่ได้หลายอย่างในประโยค ทั้งนี้มักจะขึ้นอยู่กับตำแหน่งของคำนามซึ่งแสดงความสัมพันธ์ของคำนามนั้นกับคำอื่นๆ 
                ในประโยคดังที่สรุปในตารางต่อไปนี้
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black">หน้าที่</th>
                    <th class="text-background-white-black">การใช้</th>
                    <th class="text-background-white-black">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td class="list"><b>1) ประธาน (Subject)</b></td>
                    <td>อยู่ต้นประโยค และอยู่หน้าคำกริยา</td>
                    <td><b>John</b> bought many books.</td>
                </tr>
                <tr>
                    <td class="list"><b>2) กรรม (Object)</b></td>
                    <td>อยู่หลังคำกริยาที่ต้องการกรรม</td>
                    <td>John bought many <b>books.</b></td>
                </tr>
                <tr>
                    <td class="list"><b>3) กรรมหลังบุพบท (Object of a Preposition)</b></td>
                    <td>อยู่หลังคำบุพบท</td>
                    <td>John sent an e-mail to his <b>friends</b></td>
                </tr>
                <tr>
                    <td class="list"><b>4) ส่วนเติมเต็ม (Complement)</b></td>
                    <td>อยู่หลังกริยา be, have, become</td>
                    <td>John is an <b>engineer.</b></td>
                </tr>
                <tr>
                    <td class="list"><b>5) แสดงความเป็นเจ้าของ (Possessive)</b></td>
                    <td>เติม 's ท้ายคำนามที่มีชีวิต หรือ เติม ' ท้ายคำนามที่ลงท้ายด้วย s และใช้ of + คำนามที่ไม่มีชีวิต</td>
                    <td>the <b>boy's</b> pen, the <b>kids'</b> book, the door of the <b>car</b>, the capital of <b>France</b></td>
                </tr>
            </table>
        </section>
    </div>
    <div>
        <a href="{% url 'English:exercise' 2 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content20.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 20 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content3.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div class="container">
        <section>
            <div class="inline-block">
                <div class="main-number">
                    3
                </div>
            </div>
            <div class="inline-block">
                <div class="head">
                    ARTICLE 
                    <br> 
                    (คำนำหน้านาม)
                </div>
            </div>
        </section>

        <section>
            <div class="sub-head">
                ความหมาย
            </div>
            <p>
                <b>Article</b> หมายถึง คำที่ใช้นำหน้านาม 
                เพื่อบ่งบอกรายละเอียดว่าคำนามนั้นเป็นรูปเอกพจน์หรือพหูพจน์
                รวมทั้งบ่งชี้ว่าเป็นการกล่าวถึงคำนามนั้นโดยชี้เฉยาะหรือไม่ชี้เฉพาะ 
                การใช้คำนำหน้านามนี้สามารถสรุปเป็น 2 
                ประเภทตามลักษณะการใช้ได้ดังตาราง
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black" style="width: 40%;">ประเภท</th>
                    <th class="text-background-white-black" style="width: 37%;">การใช้</th>
                    <th class="text-background-white-black" style="width: 23%;">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td rowspan="2" class="list">
                        <b>1) Indefinite Article (ไม่ชี้เฉพาะ)</b>
                        <br>
                        วางหน้านามนับได้เอกพจน์ เมื่อกล่าวโดยทั่วไป ไม่ชี้เฉพาะว่าเป็นคนไหนหรือสิ่งไหน
                    </td>
                    <td><b>a</b> + นามที่ขึ้นต้นด้วย<b>เสียงพยัญชนะ</b> (ไม่ใช่เสียง อ)</td>
                    <td>a boy, a city, a house, a unit, a university</td>
                </tr>
                <tr>
                    <td><b>an</b> + นามที่ขึ้นต้นด้วย<b>เสียงสระ</b> (เสียง อ)</td>
                    <td>an egg, an umbrella, an orange, an hour</td>
                </tr>
                <tr>
                    <td rowspan="2" class="list">
                        <b>2) Definite Article (ชี้เฉพาะ)</b>
                        <br>
                        วางหน้านามนับได้หรือนามนับไม่ได้ก็ได้ เมื่อกล่าวโดยชี้เฉพาะว่าเป็นคนไหนหรือสิ่งไหน
                    </td>
                    <td><b>the</b> (อ่านว่า เดอะ) + นามที่ขึ้นต้นด้วย<b>เสียงพยัญชนะ</b></td>
                    <td>the book, the uniform, the horse, the woman</td>
                </tr>
                <tr>
                    <td><b>the</b> (อ่านว่า ดิ) + นามที่ขึ้นต้นด้วย<b>เสียงสระ</b></td>
                    <td>the apple, the elephant, the album, the engineer</td>
                </tr>
            </table>
        </section>

        <section>
            <div class="sub-head">
                การใช้ a / an
            </div>
            <p>
                โดยทั่วไปแล้ว การใช้ Indefinite Article ด้วยคำว่า a / an 
                จะใช้นำหน้าคำนามเอกพจน์ทั่วไปโดยไม่ชี้เฉพาะเจาะจง 
                อย่างไรก็ตามอาจพบการใช้ในกรณีอื่นๆ ได้เพิ่มเติมดังที่สรุปในตารางต่อไปนี้
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black">การใช้</th>
                    <th class="text-background-white-black">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td class="list">1) นำหน้านามนับได้เอกพจน์ โดยไม่ชี้เฉพาะเจาะจง</td>
                    <td>I eat <u>an orange</u> after every meal.</td>
                </tr>
                <tr>
                    <td class="list">2) นำหน้านามเมื่อกล่าวถึงนามนั้นเป็นครั้งแรก</td>
                    <td>We went to <u>a restaurant</u> yesterday.</td>
                </tr>
                <tr>
                    <td class="list">3) นำหน้านามเมื่อแสดงถึงนามนั้นทั้งจำพวก</td>
                    <td><u>An elephant</u> is a friendly animal.</td>
                </tr>
                <tr>
                    <td class="list">4) นำหน้านามที่บ่งบอกอาชีพหรือสัญชาติ</td>
                    <td>My friend is <u>a dentist</u>. He is <u>an American</u>.</td>
                </tr>
                <tr>
                    <td class="list">5) นำหน้านามเอกพจน์ เพื่แสดงหน่วยหรืออัตราการวัด</td>
                    <td>He drives eighty miles <u>an hour</u>.</td>
                </tr>
            </table>
        </section>

        <section>
            <div class="sub-head">
                การใช้ the
            </div>
            <p>
                โดยหลักการทั่วไป การใช้ Definite Article ด้วยคำว่า the จะใช้นำหน้าคำนามได้ทุกประเภท
                ไม่ว่าจะเป็นนามเอกพจน์หรือพหูพจน์ รวมถึงนามนับได้หรือนับไม่ได้ สามารถสรุปได้ดังนี้
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black" style="width: 60%;">การใช้</th>
                    <th class="text-background-white-black" style="width: 40%;">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td class="list">1) นำหน้านามเมื่อกล่าวถึงนามนั้นมาก่อนหน้านี้แล้ว</td>
                    <td>We met a girl. <u>The girl</u> is very pretty.</td>
                </tr>
                <tr>
                    <td class="list">2) นำหน้านามที่มีส่วนขยายตามมา</td>
                    <td><u>The man</u> in that corner is my neighbor.</td>
                </tr>
                <tr>
                    <td class="list">3) นำหน้านามเมื่อทราบว่านามนั้นหมายถึงคนหรือสิ่งไหน</td>
                    <td>We have to go to <u>the post office</u>.</td>
                </tr>
                <tr>
                    <td class="list">4) นำหน้านามเมื่อนามนั้นมีเพียงสิ่งเดียวในโลก</td>
                    <td>My son wants to travel around <u>the world</u>.</td>
                </tr>
                <tr>
                    <td class="list">5) นำหน้าคำแสดงลำดับที่</td>
                    <td><u>The first son</u> of my family is James.</td>
                </tr>
                <tr>
                    <td class="list">6) นำหน้าการเปรียบเทียบ adjective และ adverb ขั้นสูงสุด</td>
                    <td>Tom is <u>the best student</u> in our class.</td>
                </tr>
                <tr>
                    <td class="list">7) นำหน้า adjective เมื่อใช้แทนนามพหูพจน์ และมีความหมายว่าคนทั้งกลุ่ม</td>
                    <td><u>The injured</u> were taken to the hospital last night.</td>
                </tr>
                <tr>
                    <td class="list">8) นำหน้านามที่เป็นชื่อสถานที่ทางภูมิศาสตร์ เช่น แม่น้ำ มหาสมุทร ทะเล คลอง อ่าว</td>
                    <td><u>The Amazon</u> is the world's largest rain forest and river system.</td>
                </tr>

            </table>
        </section>
        
        <section>
            <div class="sub-head">
                การละ article
            </div>
            <p>
                นอกเหนือจากการใช้ a / an / the ตามหลักการที่ได้สรุปไว้ข้างต้นแล้ว 
                เราอาจพบการละ article ได้ในหลายกรณีดังตารางต่อไปนี้
            </p>
            <table>
                <tr>
                    <th class="text-background-white-black" style="width: 60%;">การใช้</th>
                    <th class="text-background-white-black" style="width: 40%;">ตัวอย่าง</th>
                </tr>
                <tr>
                    <td class="list">1) นามนับไม่ได้ / นามนับได้พหูพจน์ที่ไม่ชี้เฉพาะ</td>
                    <td><u>Water</u> is necessary for life.</td>
                </tr>
                <tr>
                    <td class="list">2) ชื่อวิชา / ภาษา</td>
                    <td>They study <u>English</u> four times a week.</td>
                </tr>
                <tr>
                    <td class="list">3) กีฬา</td>
                    <td>Mike is playing <u>football</u> with his friends.</td>
                </tr>
                <tr>
                    <td class="list">4) มื้ออาหาร</td>
                    <td>I always have <u>breakfast</u> at 8 o'clock.</td>
                </tr>
                <tr>
                    <td class="list">5) ฤดูกาล / วันหยุด / เทศกาล</td>
                    <td><u>Summer</u> is the best time for relaxation.</td>
                </tr>
                <tr>
                    <td class="list">6) วัน / เดือน / ปี</td>
                    <td>She wants to meet you on <u>Wednesday</u>.</td>
                </tr>
                <tr>
                    <td class="list">7) สถานที่ เช่น ถนน เมือง ประเทศ รัฐ ทวีป โรงเรียน</td>
                    <td>We have never been to <u>Europe</u>.</td>
                </tr>
                <tr>
                    <td class="list">8) โรคภัยไข้เจ็บ</td>
                    <td>In the past many people died of <u>malaria</u>.</td>
                </tr>
                <tr>
                    <td class="list">9) สถานที่ เมื่อไปตามจุดประสงค์ของสถานที่นั้นๆ (ใช้ the นำหน้าถ้าไปเพื่อจุดประสงค์อื่น)</td>
                    <td>These children go to <u>school</u> every day.</td>
                </tr>
            </table>
        </section>
    </div>
    <div>
        <a href="{% url 'English:exercise' 3 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>

English/templates/English/basic_english/contents/content7.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'English/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contents</title>
</head>

<body>
    <div>
        In hurry!
    </div>
    <div>
        <a href="{% url 'English:exercise' 7 %}" target="_blank">Let's go to exercise</a>
    </div>
</body>

</html>